// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_MessageContainer = NULL;
lv_obj_t * ui_TitleLabel = NULL;
lv_obj_t * ui_MsgLabel = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
// event funtions
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        fetchData(e);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MessageContainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_MessageContainer);
    lv_obj_set_width(ui_MessageContainer, 760);
    lv_obj_set_height(ui_MessageContainer, 200);
    lv_obj_set_x(ui_MessageContainer, 0);
    lv_obj_set_y(ui_MessageContainer, -120);
    lv_obj_set_align(ui_MessageContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MessageContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_MessageContainer, lv_color_hex(0xFCF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MessageContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MessageContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MessageContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MessageContainer, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MessageContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MessageContainer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MessageContainer, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleLabel = lv_label_create(ui_MessageContainer);
    lv_obj_set_width(ui_TitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleLabel, -1);
    lv_obj_set_y(ui_TitleLabel, -77);
    lv_obj_set_align(ui_TitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleLabel, "Here is a place for a message title");

    ui_MsgLabel = lv_label_create(ui_MessageContainer);
    lv_obj_set_width(ui_MsgLabel, lv_pct(100));
    lv_obj_set_height(ui_MsgLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MsgLabel, 0);
    lv_obj_set_y(ui_MsgLabel, 20);
    lv_obj_set_align(ui_MsgLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MsgLabel, "This is a sample message that wraps when is too long");

    ui_Button1 = lv_button_create(ui_MainScreen);
    lv_obj_set_width(ui_Button1, 369);
    lv_obj_set_height(ui_Button1, 192);
    lv_obj_set_x(ui_Button1, -205);
    lv_obj_set_y(ui_Button1, 114);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_MainScreen);
    lv_obj_set_width(ui_Button2, 369);
    lv_obj_set_height(ui_Button2, 192);
    lv_obj_set_x(ui_Button2, 204);
    lv_obj_set_y(ui_Button2, 114);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_MessageContainer = NULL;
    ui_TitleLabel = NULL;
    ui_MsgLabel = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;

}
