// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "ui.h"

void fetchData(lv_event_t * e)
{
	// Your code here
}
